#!/usr/bin/env python
import sys
import shlex
import argparse
import subprocess

def handle_compound_command(tokens):
   pass 

def handle_line(line):
    tokens = shlex.split(line, posix=True)
    if len(tokens) == 0:
        return

    if tokens[0] == 'make':
        pass
    elif tokens[0] == '/usr/bin/cmake':
        pass
    elif tokens[0] == 'echo':
        pass
    else:
        print 'Unknown command:', tokens

make_process = subprocess.Popen(['make', '-j1', 'VERBOSE=1'], stdout=subprocess.PIPE)
while True:
    line = make_process.stdout.readline()
    if line == '':
        break
    handle_line(line)
